import { experience, projects } from '../profile';

// Workflow sections organize the responsibilities in the CV; they are not dated milestones.
const roleContent = [
  {id:'makerpath',summary:'Develop OxiNote’s cross-platform interface, Markdown editor, and reliable offline storage.',tools:['React Native','TypeScript','Markdown','JSON storage'],projectNumbers:[10],process:[['Foundation & UX','Define the technical foundation, feature-based architecture, local data strategy, and note-management UX patterns.'],['Application development','Build reusable React Native components, the Markdown editor, and image/file import with resize and preview behavior.'],['Data reliability','Implement authentication, CRUD, local JSON storage, and stable file/asset references for offline use.']]},
  {id:'dcmvn',summary:'Develop Revit automation tools and coordinate MEPF models across multidisciplinary projects.',tools:['C# / .NET','Revit API','WPF','Python','Revit','AutoCAD','Revizto','Navisworks','BIMcollab','Git / GitLab'],projectNumbers:[34,35,36,37,38,39,40,41,2,4,5,6,7,15,16,18,19,22,23,33,42,43,44],process:[['Production requirements','Translate BIM/MEP requirements into practical automation for sheets, family placement, parameters, MEP generation, routing, and model checks.'],['Tools & models','Work with Revit elements, geometry, connectors, and systems; develop internal add-ins and design coordinated MEPF models.'],['Coordination & maintenance','Resolve clashes, review model data, create as-built models from Point Cloud, and debug, maintain, and document tool code.']]},
  {id:'mindx',summary:'Build responsive React interfaces and REST APIs with authentication, validation, and database integration.',tools:['React','Node.js','Express.js','MongoDB','JWT','Git','Figma'],projectNumbers:[11,12,13,14],process:[['Frontend implementation','Translate Figma designs into responsive React interfaces with reusable components, routing, state management, and forms.'],['Backend integration','Design REST APIs and MongoDB models; implement JWT authentication, authorization, middleware, validation, and CRUD.'],['Review & improvements','Debug frontend/backend issues, use Git workflows, participate in code reviews, and propose practical improvements.']]},
  {id:'armo-vietnam',summary:'Design electrical systems, build Revit models, and coordinate electrical drawings with other MEP disciplines.',tools:['Revit','Electrical design','MEPF coordination','Quantity estimation'],projectNumbers:[],process:[['Design & estimation','Design electrical systems to customer requirements and calculate equipment quantities for budgeting and procurement.'],['Model coordination','Create 3D electrical models in Revit, coordinate with mechanical and plumbing disciplines, and resolve clashes.'],['Drawing delivery','Prepare electrical layouts, equipment arrangements, and coordinated drawings; revise designs as project requirements change.']]},
  {id:'cadian-vietnam',summary:'Draft electrical systems, estimate equipment quantities, and revise CAD documentation for project delivery.',tools:['CAD drafting','Electrical design','Quantity estimation','Drawing documentation'],projectNumbers:[],process:[['Requirements & quantities','Design and draft automatic electrical systems to customer requirements and estimate equipment quantities.'],['CAD documentation','Produce detailed CAD drawings and support repair and renovation work for existing buildings.'],['Revisions & checks','Incorporate customer comments and site conditions, coordinate drawing updates, and check documentation for consistency.']]},
];
export const roles = experience.map(([date,title,company,context,responsibilities],index)=>({date,title,company,context,responsibilities,...roleContent[index],projects:roleContent[index].projectNumbers.map(number=>projects.find(project=>project.id===`hoa-project-${number}`)).filter(Boolean)}));
