import { useEffect, useId, useRef, useState } from 'react'
import type { FormEvent } from 'react'
import './App.css'

type Category = 'Tất cả' | 'MEP & BIM' | 'Automation' | 'Web development'
type Project = { id: string; category: Category; title: string; description: string; tags: string[]; visual: string; scope: string[] }
const projects: Project[] = [
 { id: '01', category: 'MEP & BIM', title: 'Hệ thống MEP · Office Tower', description: 'Từ thiết kế hệ thống đến phối hợp mô hình BIM đa bộ môn.', tags: ['Revit MEP', 'Navisworks', 'HVAC'], visual: 'building', scope: ['Xây dựng mô hình HVAC, cấp thoát nước và điện.', 'Phối hợp không gian kỹ thuật và rà soát xung đột.', 'Triển khai bản vẽ, schedules và khối lượng từ mô hình.'] },
 { id: '02', category: 'Automation', title: 'Revit Workflow Toolkit', description: 'Biến những thao tác lặp lại thành quy trình tự động có kiểm soát.', tags: ['Python', 'Dynamo', 'Revit API'], visual: 'code', scope: ['Kiểm tra và chuẩn hóa thông tin phần tử.', 'Tự động tạo sheets và cập nhật parameters.', 'Xuất dữ liệu mô hình để kiểm tra và báo cáo.'] },
 { id: '03', category: 'Web development', title: 'BIM Project Dashboard', description: 'Kết nối dữ liệu kỹ thuật với một giao diện web trực quan.', tags: ['React', 'TypeScript', 'Node.js'], visual: 'dashboard', scope: ['Dashboard theo dõi dữ liệu và công việc theo bộ môn.', 'Thiết kế API, cơ sở dữ liệu và phân quyền.', 'Bộ lọc dữ liệu, biểu đồ và báo cáo cho nhóm dự án.'] },
]
function Arrow({ diagonal = false }: { diagonal?: boolean }) { return <svg width="18" height="18" viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d={diagonal ? 'M6 18 18 6M6 6h12v12' : 'M4 12h16m-6-6 6 6-6 6'} stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round" /></svg> }
function TechnicalModel({ compact = false }: { compact?: boolean }) {
 const modelId = useId()
 return <svg className={compact ? 'technical-model compact' : 'technical-model'} viewBox="0 0 600 490" fill="none" role="img" aria-label="Sơ đồ không gian hệ thống MEP với đường ống, ống gió và kết cấu công trình">
 <defs><pattern id={modelId + '-grid'} width="32" height="32" patternUnits="userSpaceOnUse"><path d="M32 0H0V32" stroke="#ccd1cd" strokeWidth=".6"/></pattern><linearGradient id={modelId + '-slab'} x1="100" y1="100" x2="500" y2="400"><stop stopColor="#e2e5df"/><stop offset="1" stopColor="#bcc5bd"/></linearGradient></defs>
 <rect width="600" height="490" fill={`url(#${modelId + '-grid'})`} opacity=".55"/>
 <g stroke="#a5b0a7" strokeWidth="1"><path d="m62 328 265-155 227 130-266 157Z" fill="#dce2db" fillOpacity=".5"/><path d="m62 305 265-155 227 130-266 157Z" fill={`url(#${modelId + '-slab'})`}/><path d="M62 305v23l226 132v-23m266-157v23M327 150v23"/><path d="m81 167 246-143 207 120-246 143Z" fill="#f4f5ef" fillOpacity=".67"/><path d="M81 167v138m246-281v126m207-6v136M288 287v150" strokeWidth="9"/><path d="m81 167 207 120 246-143M327 24 81 167" strokeWidth="7"/><path d="m88 333 246-142m-207 168 246-144m-207 167 246-143m-207 166 246-143m-210-39 226 130m-188-153 226 130m-188-152 226 130m-188-152 226 130" opacity=".4"/></g>
 <g strokeLinejoin="round"><path d="m119 208 84 48 160-93 105 61" stroke="#697f75" strokeWidth="33"/><path d="m119 199 84 48 160-93 105 61" stroke="#a3b7a9" strokeWidth="27"/><path d="m119 187 84 48 160-93 105 61" stroke="#c4d2c5" strokeWidth="2"/><path d="m204 247 0 41 77 45" stroke="#8ba091" strokeWidth="22"/><path d="m208 249 0 35 77 45" stroke="#bbccbd" strokeWidth="16"/>
 <path d="m113 274 93 54 212-122 66 39v46" stroke="#99482a" strokeWidth="12"/><path d="m113 270 93 54 212-122 66 39v46" stroke="#e77946" strokeWidth="8"/><path d="m170 301 0-44 74-43m86 38v-48l78-46" stroke="#e77946" strokeWidth="7"/>
 <path d="m138 290 67 39 226-130 66 38v57" stroke="#4a777b" strokeWidth="7"/><path d="m138 287 67 39 226-130 66 38v57" stroke="#8baeb0" strokeWidth="4"/>
 <path d="m119 152 68 39 156-90 80 46" stroke="#d3b679" strokeWidth="10"/><path d="m119 148 68 39 156-90 80 46" stroke="#e7ce92" strokeWidth="6"/></g>
 <g fill="#e9ede6" stroke="#6b8072"><path d="m256 326 28-16 30 18-28 16Z"/><path d="m256 326 0 10 30 18v-10m0 10 28-16v-10"/><path d="m445 213 29-17 28 17-29 17Z"/><path d="M445 213v12l28 17v-12m0 12 29-17v-12"/></g>
 <g stroke="#77867a" strokeWidth="1" strokeDasharray="3 4"><path d="M167 209V113H78m331 125 64 37h81M289 375v47h-90"/></g>
 {!compact && <g fontFamily="monospace" fontSize="10" fill="#59655b"><text x="48" y="102">01 / HVAC DUCT</text><text x="457" y="291">02 / PIPING</text><text x="120" y="439">03 / COORDINATION</text></g>}
 <g fill="#e77946"><circle cx="167" cy="209" r="4"/><circle cx="409" cy="238" r="4"/><circle cx="289" cy="375" r="4"/></g></svg>
}
function ProjectVisual({ kind }: { kind: string }) {
 if (kind === 'building') return <div className="project-art model-art"><TechnicalModel compact/><span className="art-caption">COORDINATED MODEL / LOD 300</span></div>
 if (kind === 'code') return <div className="project-art code-art"><div className="code-window"><div className="window-top"><span/><span/><span/><small>mep_toolkit.py</small></div><div className="code-lines"><div><i>01</i><em>from</em> revit <em>import</em> DB</div><div><i>02</i></div><div><i>03</i><em>def</em> <b>automate_workflow</b>(doc):</div><div><i>04</i>  elements = <b>collect</b>(doc)</div><div><i>05</i>  <em>for</em> item <em>in</em> elements:</div><div><i>06</i>    <b>update_parameters</b>(item)</div><div><i>07</i>  <em>return</em> <strong>"All set ✓"</strong></div></div><div className="code-status"><span/> Workflow completed <small>↵</small></div></div></div>
 return <div className="project-art dashboard-art"><div className="mini-dashboard"><div className="mini-sidebar"><b>◈</b><span/><span/><span/><span/></div><div className="mini-main"><div className="mini-header">Project overview <span>↗</span></div><div className="mini-stats"><div><small>ELEMENTS</small><b>2,486</b></div><div><small>COORDINATION</small><b>94<span>%</span></b></div></div><div className="mini-chart">{[35,55,46,68,59,85,74,96].map((height,i) => <span key={i} style={{height:`${height}%`}}/>)}</div><div className="mini-bottom">MODEL HEALTH <span>● All systems connected</span></div></div></div></div>
}
function App() {
 const [filter, setFilter] = useState<Category>('Tất cả')
 const [selected, setSelected] = useState<Project | null>(null)
 const [menu, setMenu] = useState(false)
 const [saved, setSaved] = useState(false)
 const dialog = useRef<HTMLDialogElement>(null)
 useEffect(() => { if (selected) dialog.current?.showModal(); else dialog.current?.close() }, [selected])
 function saveBrief(e: FormEvent<HTMLFormElement>) {
  e.preventDefault()
  const data = new FormData(e.currentTarget)
  const text = `PROJECT BRIEF\n\nTên: ${data.get('name')}\nEmail: ${data.get('email')}\nLĩnh vực: ${data.get('service')}\n\n${data.get('message')}\n`
  const url = URL.createObjectURL(new Blob([text], {type:'text/plain;charset=utf-8'}))
  const link = document.createElement('a'); link.href = url; link.download = 'project-brief.txt'; link.click(); URL.revokeObjectURL(url); setSaved(true)
 }
 return <>
 <header className="site-header"><a className="brand" href="#home" aria-label="Hoa Le — Trang chủ"><span className="brand-icon">h<span>.</span></span><span>HOA LE<span className="brand-sub">ENGINEER & DEVELOPER</span></span></a><button className="menu-toggle" onClick={() => setMenu(!menu)} aria-expanded={menu} aria-label="Mở menu">{menu ? 'Đóng ✕' : 'Menu ☰'}</button><nav className={menu ? 'open' : ''} aria-label="Điều hướng chính">{[['Chuyên môn','expertise'],['Dự án','projects'],['Về tôi','about']].map(([name,id]) => <a key={id} href={`#${id}`} onClick={() => setMenu(false)}>{name}</a>)}<a className="nav-contact" href="#contact" onClick={() => setMenu(false)}>Cùng hợp tác <Arrow diagonal/></a></nav></header>
 <main>
 <section className="hero section-shell" id="home"><div className="hero-copy"><div className="eyebrow"><span className="tiny-line"/> ENGINEERING MEETS TECHNOLOGY</div><h1>Thiết kế hệ thống.<br/>Kết nối dữ liệu.<br/><span>Tạo nên giá trị.</span></h1><p className="hero-description">Tôi kết nối kỹ thuật MEP, mô hình BIM và lập trình để xây dựng những giải pháp thông minh — từ công trình đến môi trường số.</p><div className="hero-actions"><a className="button primary" href="#projects">Khám phá dự án <Arrow/></a><a className="text-link" href="#about">Một chút về tôi <Arrow diagonal/></a></div><div className="hero-note"><span className="status-dot"/> MEP Engineer <span className="note-divider">/</span> BIM Specialist <span className="note-divider">/</span> Developer</div></div><div className="hero-visual"><div className="visual-top"><span><span className="status-dot"/> SYSTEMS IN SYNC</span><span>MODEL_001</span></div><TechnicalModel/><div className="model-legend"><span><i className="legend-hvac"/> HVAC</span><span><i className="legend-pipe"/> PIPING</span><span><i className="legend-electrical"/> ELECTRICAL</span></div><div className="visual-bottom"><span>THE INTERSECTION OF DESIGN & CODE</span><span>↗</span></div></div></section>
 <div className="tool-strip section-shell"><span>Ý TƯỞNG → GIẢI PHÁP</span><div>Revit <span className="tool-divider">/</span> Navisworks <span className="tool-divider">/</span> Dynamo <span className="tool-divider">/</span> Python <span className="tool-divider">/</span> React <span className="tool-divider">/</span> Node.js</div></div>
 <section className="section-shell expertise-section" id="expertise"><div className="section-heading"><div><div className="eyebrow">01 / CHUYÊN MÔN</div><h2>Bốn lĩnh vực.<br/>Một tư duy giải quyết vấn đề.</h2></div><p>Tư duy kỹ thuật làm nền tảng.<br/>Công nghệ mở rộng khả năng.</p></div><div className="expertise-grid">{[
 ['01','⌁','MEP Engineering','Thiết kế hệ thống cơ điện với sự cân bằng giữa hiệu năng, tính khả thi và khả năng vận hành.','HVAC · Electrical · Plumbing'],['02','◇','Revit MEP & BIM','Chuyển thiết kế thành mô hình thông tin rõ ràng, đồng bộ và sẵn sàng phối hợp.','Modeling · Coordination · Documentation'],['03','⌘','Automation','Đơn giản hóa công việc lặp lại, chuẩn hóa dữ liệu và dành thời gian cho điều quan trọng.','Python · Dynamo · Revit API'],['04','</>','Full Stack Web','Xây dựng ứng dụng từ giao diện đến dữ liệu, đưa quy trình kỹ thuật lên nền tảng số.','React · TypeScript · Node.js'],
 ].map(([number,icon,title,description,tools]) => <article className="expertise-card" key={number}><div className="expertise-top"><span className="expertise-icon">{icon}</span><span>{number}</span></div><h3>{title}</h3><p>{description}</p><div className="expertise-tools">{tools}</div></article>)}</div></section>
 <section className="projects-section" id="projects"><div className="section-shell"><div className="section-heading"><div><div className="eyebrow">02 / DỰ ÁN TIÊU BIỂU</div><h2>Từ ý tưởng đến ứng dụng.</h2></div><span className="sample-note">Danh mục minh họa · Chờ cập nhật dự án thực tế</span></div><div className="project-filters" aria-label="Lọc dự án">{(['Tất cả','MEP & BIM','Automation','Web development'] as Category[]).map(category => <button aria-pressed={filter === category} className={filter === category ? 'active' : ''} onClick={() => setFilter(category)} key={category}>{category}{category === 'Tất cả' && <span>03</span>}</button>)}</div><div className="project-grid">{projects.filter(project => filter === 'Tất cả' || project.category === filter).map(project => <button className="project-card" key={project.id} onClick={() => setSelected(project)}><ProjectVisual kind={project.visual}/><div className="project-category">{project.category}<span>CONCEPT / {project.id}</span></div><div className="project-title"><h3>{project.title}</h3><Arrow diagonal/></div><p>{project.description}</p><div className="tags">{project.tags.map(tag => <span key={tag}>{tag}</span>)}</div></button>)}</div></div></section>
 <section className="about-section section-shell" id="about"><div className="about-graphic"><span className="eyebrow">MY APPROACH</span><div className="approach-circle"><div className="orbit-label label-top">ENGINEERING</div><div className="orbit-label label-bottom">DEVELOPMENT</div><span className="approach-symbol">h<span>.</span></span><div className="orbit-dot"/></div><div className="graphic-footer">BUILD WITH LOGIC. DESIGN WITH PURPOSE.</div></div><div className="about-copy"><div className="eyebrow">03 / VỀ TÔI</div><h2>Kỹ thuật là nền tảng.<br/><span>Sáng tạo là động lực.</span></h2><p>Tôi quan tâm đến điểm giao giữa công trình và công nghệ: nơi một mô hình Revit có thể trở thành nguồn dữ liệu, một đoạn code có thể cải thiện quy trình, và một ứng dụng web có thể kết nối cả đội ngũ.</p><p>Cách tôi tiếp cận công việc bắt đầu từ việc hiểu vấn đề, xây dựng giải pháp rõ ràng và liên tục cải tiến để mang lại giá trị thiết thực.</p><div className="approach-values"><span><b>01</b> Hiểu đúng vấn đề</span><span><b>02</b> Xây dựng có hệ thống</span><span><b>03</b> Cải tiến liên tục</span></div></div></section>
 <section className="contact-section" id="contact"><div className="section-shell contact-layout"><div><div className="eyebrow">04 / KẾT NỐI</div><h2>Có một ý tưởng?<br/><span>Cùng xây dựng nó.</span></h2><p>Một hệ thống MEP, một quy trình cần tự động hóa,<br/>hay một sản phẩm web — bắt đầu từ cuộc trò chuyện.</p><div className="contact-note"><Arrow diagonal/><span>Tạo brief cho dự án của bạn.<br/><small>Thông tin liên hệ sẽ được cập nhật theo hồ sơ thực tế.</small></span></div></div><form onSubmit={saveBrief} onChange={() => setSaved(false)}><div className="form-row"><label>Tên của bạn<input name="name" placeholder="Nguyễn Văn A" autoComplete="name" required maxLength={100}/></label><label>Email<input name="email" type="email" placeholder="you@company.com" autoComplete="email" required/></label></div><label>Bạn quan tâm đến<select name="service"><option>MEP & Revit BIM</option><option>Automation</option><option>Full Stack Web</option><option>Hợp tác khác</option></select></label><label>Chia sẻ ý tưởng<textarea name="message" placeholder="Bạn muốn xây dựng hoặc cải thiện điều gì?" required rows={3} maxLength={5000}/></label><button className="button primary" type="submit">Tải brief dự án <Arrow diagonal/></button><p className="form-feedback" role="status">{saved ? 'Đã tạo brief! File được tải về máy để bạn lưu hoặc chia sẻ.' : 'Brief được tải về máy của bạn; biểu mẫu chưa gửi email.'}</p></form></div></section>
 </main><footer className="section-shell"><a className="footer-brand" href="#home">HOA LE<span> / ENGINEER & DEVELOPER</span></a><span>Thiết kế có mục đích. Xây dựng bằng đam mê.</span><a href="#home">Về đầu trang ↑</a></footer>
 <dialog ref={dialog} onCancel={() => setSelected(null)} onClick={e => {if (e.target === e.currentTarget) setSelected(null)}} aria-labelledby="project-dialog-title">{selected && <div className="dialog-content"><button className="dialog-close" onClick={() => setSelected(null)} aria-label="Đóng chi tiết dự án">✕</button><div className="eyebrow">DỰ ÁN MINH HỌA / {selected.category}</div><h2 id="project-dialog-title">{selected.title}</h2><ProjectVisual kind={selected.visual}/><p>{selected.description}</p><h3>Phạm vi đề xuất</h3><ul>{selected.scope.map(item => <li key={item}>{item}</li>)}</ul><div className="tags">{selected.tags.map(tag => <span key={tag}>{tag}</span>)}</div><p className="dialog-disclaimer">Đây là concept minh họa cho portfolio, chưa phải thông tin về dự án đã hoàn thành.</p><a className="button primary" href="#contact" onClick={() => setSelected(null)}>Trao đổi về dự án tương tự <Arrow/></a></div>}</dialog>
 </>
}
export default App

